### ISSUE TITLE
Support for axios interceptors?

### ISSUE THREAD

**Issue by raniesantos** [spatie/form-backend-validation#13]
I am using this package along with `tymon/jwt-auth` in the backend. I was able to implement axios interceptors to catch certain error responses from jwt-auth.

However, on requests where I use the Form class instead of plain axios, I am unable to intercept the error responses. How do I implement this?

Note: I am aware that when using this package, the data can be accessed through `error.data` instead of `error.response.data` so I am sure that I am not incorrectly accessing the data.

**Comment by sebastiandedeyne** [comment]
Never used interceptors myself so could be wrong—but aren't interceptors registered on the global `axios` object? In that case, they should be applied in the form. Are you sure your project only has one version (and in turn, instance) of axios?

**Comment by raniesantos** [comment]
Well in my package.json this is what my dependencies look like, is it an issue that I have axios here even though form-backend-validation is already installed?
```
"devDependencies": {
	"axios": "^0.16.1",
	"babel-preset-es2015": "^6.24.1",
	"babel-preset-stage-2": "^6.24.1",
	"bulma": "^0.4.0",
	"font-awesome": "^4.7.0",
	"form-backend-validation": "^1.4.0",
	"izitoast": "^1.1.1",
	"laravel-mix": "^0.10.0",
	"moment": "^2.18.1",
	"urelios": "^1.0.8",
	"vue": "^2.2.6",
	"vue-router": "^2.4.0",
	"vuex": "^2.3.0"
}
```

**Comment by sebastiandedeyne** [comment]
Dependencies listed in your `package.json` aren't the same as your *installed* dependencies, since your packages dependencies each have their own dependencies, which in turn have their own dependencies etc. This turns into a dependency tree which can be viewed with `npm list`.

You've specified `axios@^0.16`, while this package requires `axios@^0.15`. Since these aren't compatible according to semver, your application most likely has axios bundled twice, and your interceptors only apply to the other version (as stated, issues like this can be debugged via `npm list`).

Since 0.16 is the higher version, this one would be preferable. Axios is a widely used (singleton!) library, so it would make sense for this package to require it as a peer dependency instead. I'll decide what to do with this next week. If you need this to be fixed sooner, downgrade your own axios version to `^0.15`.

Note that if you or we would upgrade axios to a higher version (0.17+) you could run into the same issue again in the future!

**Comment by freekmurze** [comment]
Requiring axios as a peer dependency seems like the way to go. I'll discuss it further with @sebastiandedeyne next week and make the necessary changes.

**Comment by raniesantos** [comment]
@freekmurze @sebastiandedeyne Thanks, I will be testing this again after fixing my dependencies once I get the time. Hopefully I can get it to work and close this issue.

**Comment by raniesantos** [comment]
Closing issue, I got it to work after removing the relevant dependencies and only reinstalling the form class. Sorry for bothering you @freekmurze @sebastiandedeyne.

**Comment by sebastiandedeyne** [comment]
As of v1.4.1, axios is a peer dependency, so you'll need to install it in your application!
