### ISSUE TITLE
[Question] A good way to clear errors

### ISSUE THREAD

**Issue by sausin** [spatie/form-backend-validation#19]
First off, thanks for the good work in maintaining this package! :+1: 

In the laracasts video, jeffery was using `@keydown` as an example on the form to clear errors. However, this approach doesn't work with `select` inputs. I have the following scheme right now:

```javascript
<template>
    <form @submit.prevent="onSubmit" @keydown="form.errors.clear($event.target.name)" @change="errClear($event.target.tagName, $event.target.name, $event.target.value)">
...
...
</template>

<script>
...
        methods: {
            // error clearing setup for SELECT type fields
            errClear(type, name, value) {
                if (type === 'SELECT') {
                    this.form.errors.clear(name);
                }
            }
        }
...
</script>
```

This almost works out correctly, except for the field defined with `number` inputs. If the up / down arrow buttons are used, the errors don't clear as it's not covered by either of the above two.

I tried `@input` event but that doesn't work until the field loses focus so it doesn't give the user a consistent behavior.

So the question is, what are you guys using? :smile:

**Comment by sebastiandedeyne** [comment]
Unfortunately I don't think there's a truly clean way to handle every case, since DOM events are fairly inconsistent. *(Side note: React handles this better than Vue since `onChange` just works everywhere)*

Alternatively, if you have a few exceptions in your input fields, you could register an event listener on the elements themselves to not clutter your form. 

You could also create wrapper components for your input fields, like your own `number` input, which could also emit a change event when the arrows are clicked.

Sorry, don't really have a clear answer, but hope this helps!

**Comment by sausin** [comment]
@sebastiandedeyne Thanks! Just wanted to know if it was possible to do it better.

I will use this setup for now :+1:
