### ISSUE TITLE
detecting a dirty form

### ISSUE THREAD

**Issue by devinfd** [spatie/form-backend-validation#45]
I'm looking for a way to determine if a form is "dirty" ie: any of the original data has changed. Is there such a way or could that be added as a flag into Form.js?

**Comment by sebastiandedeyne** [comment]
This currently isn't possible, and I don't think we're going to add this either since we'd probably need to maintain an entire reactivity system.

If your browser support policy allows it, you could use something like a proxy to wrap the object before passing it to the form, and listen for changes yourself.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by devinfd** [comment]
Yeah that’s pretty much what I thought as well.

- Devin Dombrowski
