### ISSUE TITLE
2.3.3 Update broke my inputs.

### ISSUE THREAD

**Issue by raniesantos** [spatie/form-backend-validation#66]
I was upgrading frontend packages on a project.

After upgrading, when I type into text fields not all my keypresses get registered (or they *do* get registered but something is messing up the reactivity). Some characters get entered but most of them don't.

**Details relevant to bug:**

My opening form tag looks like this:

```html
<form @submit.prevent="onSubmitSignup" @keydown="form.errors.clear($event.target.id)" novalidate>
```

If I'm using **2.3.3**, I can change it to `@keyup` and the problem goes away but `@keydown` is clearly better used in this situation.

## I tried downgrading to 2.3.2, the problem went away.

I use the Buefy component library. There's a possibility that `form-backend-validation@2.3.3` conflicts with it, but I currently have no idea what it could be.

Here are the exact versions of the packages involved (taken from lock file):

- buefy 0.6.5
- form-backend-validation 2.3.3
- vue 2.5.16

## CodeSandbox reproduction

You can fork it on CodeSandbox *without creating an account*. It will allow you to remove and install dependencies from the sidebar to try changing the package versions.

https://codesandbox.io/s/kow33p53m7

### Update

Tested against 2.3.5, bug still exists.

**Comment by sebastiandedeyne** [comment]
This is odd, it's like the event isn't propagated anymore. @nedmas Any idea what could cause this?

**Comment by nedmas** [comment]
I'm not sure what the problem is. But you can use `$nextTick` as a work around. See https://codesandbox.io/s/5zwxrpqo0l

I'll try and take a look later to see if I can properly debug it.

**Comment by nedmas** [comment]
Ok I don't think this is related to `spatie/form-backend-validation`.

The issue is in Vue. Any state change (modifying any `data` value) inside a `keydown` event will prevent the keydown input. See this example https://codesandbox.io/s/6zp3l523nr

I've checked and this behaviour changed from Vue 2.4.4 to 2.5.0. The [release notes](https://github.com/vuejs/vue/releases/tag/v2.5.0) imply that the change is deliberate.

So I would suggest using my work around from my previous post. @sebastiandedeyne I'm happy to add something to the readme if you think it would be helpful?

**Comment by raniesantos** [comment]
So would the user need manually implement that `clear()` method in every single form that uses this package?

**Comment by jackleblack-kpt** [comment]
Same issue but the @nedmas's solution won't work :(

**Comment by sebastiandedeyne** [comment]
Looks like this has been inactive for over a year. Closing this, feel free to reopen if there are still issues.
